# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0033_auto_20190130_1409'),
        ('materia', '0038_auto_20190108_1606'),
    ]

    operations = [
    ]
